# Generated by Django 4.2.27 on 2026-02-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('MA', 'Mariscos'), ('PE', 'Pescado'), ('PO', 'Pollo')], default='PE', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_presentacion', models.CharField(choices=[('VAC', 'Empacado al Vacío (Unidades)'), ('BAN', 'Bandeja (Unidades)'), ('LIB', 'A granel (Libras)')], max_length=3)),
                ('estado', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='pedidos.pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='proveedores.proveedor')),
            ],
        ),
    ]
