# Generated by Django 4.2.27 on 2026-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('MA', 'Mariscos'), ('PE', 'Pescado'), ('PO', 'Pollo')], default='MA', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('procedencia', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_prestacion', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]

# Generated by Django 4.2.27 on 2026-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('MA', 'Mariscos'), ('PE', 'Pescado'), ('PO', 'Pollo')], default='MA', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('procedencia', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_prestacion', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
