# Generated by Django 4.2.27 on 2026-02-25 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('MA', 'Mariscos'), ('PE', 'Pescado'), ('PO', 'Pollo')], default='PE', max_length=3, verbose_name='Tipo de Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('tipo_presentacion', models.CharField(choices=[('VAC', 'Empacado al Vacío (Unidades)'), ('BAN', 'Bandeja (Unidades)'), ('LIB', 'A granel (Libras)')], max_length=3, verbose_name='Presentación')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proveedores.proveedor', verbose_name='Seleccionar Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
