# Generated by Django 4.2.27 on 2026-02-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pedido',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proveedores.proveedor', verbose_name='Seleccionar Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_presentacion',
            field=models.CharField(choices=[('VAC', 'Empacado al Vacío (Unidades)'), ('BAN', 'Bandeja (Unidades)'), ('LIB', 'A granel (Libras)')], max_length=3, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('MA', 'Mariscos'), ('PE', 'Pescado'), ('PO', 'Pollo')], default='PE', max_length=3, verbose_name='Tipo de Producto'),
        ),
    ]
