# Generated by Django 4.2.27 on 2026-02-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_presentacion',
            field=models.CharField(choices=[('VAC', 'Empacado al Vacío (Unidades)'), ('BAN', 'Bandeja (Unidades)'), ('LIB', 'A granel (Libras)')], max_length=3),
        ),
    ]
