# Generated by Django 4.2.27 on 2026-03-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_stock'),
    ]

    operations = [
    ]
