# Generated by Django 4.2.27 on 2026-02-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_peso_remove_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
