# Generated by Django 4.2.27 on 2026-02-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='peso',
        ),
    ]
