# Generated by Django 4.2.27 on 2026-03-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_add_proveedor_field'),
    ]

    operations = [
    ]
