# Generated by Django 4.2.27 on 2026-02-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='recovery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recovery_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
