# Generated by Django 4.2.27 on 2026-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_options_alter_detallepedido_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='presentacion',
            field=models.CharField(blank=True, default='unidades', max_length=20, null=True),
        ),
    ]
