# Generated by Django 4.2.27 on 2026-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_detallepedido_cantidad_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('REC', 'Recibido'), ('CAN', 'Cancelado')], default='PEN', max_length=3),
        ),
    ]
