# Generated by Django 4.2.27 on 2026-02-24 16:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('PENDIENTE', 'Pendiente')], default='COMPLETADA', max_length=20)),
                ('tipo_presentacion', models.CharField(choices=[('EMPACADO_VACIO', 'Empacado al Vacío'), ('POR_LIBRA', 'Por Libra'), ('BANDEJA', 'Bandeja')], default='BANDEJA', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
