# Generated by Django 4.2.27 on 2026-02-23 13:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_peso_remove_producto_stock_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='documento_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_presentacion',
            field=models.CharField(choices=[('EMPACADO_VACIO', 'Empacado al Vacío'), ('POR_LIBRA', 'Por Libra'), ('BANDEJA', 'Bandeja')], default='BANDEJA', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
