# Generated by Django 4.2.27 on 2026-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
