# Generated by Django 4.2.27 on 2026-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cantidad_venta_documento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='documento_cliente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
