# Generated by Django 4.2.27 on 2026-03-05 16:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_stock'),
        ('ventas', '0003_alter_venta_cantidad_alter_venta_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA (19%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='documento_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_presentacion',
            field=models.CharField(blank=True, choices=[('EMPACADO_VACIO', 'Empacado al Vacío'), ('POR_LIBRA', 'Por Libra'), ('BANDEJA', 'Bandeja')], default='BANDEJA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_presentacion', models.CharField(choices=[('EMPACADO_VACIO', 'Empacado al Vacío'), ('POR_LIBRA', 'Por Libra'), ('BANDEJA', 'Bandeja')], default='BANDEJA', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
            },
        ),
    ]
