# Generated by Django 4.2.27 on 2026-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_documento_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='TIPO_PRESENTACION',
            field=models.CharField(choices=[('EMPACADO_VACIO', 'Empacado al Vacío'), ('POR_LIBRA', 'Por Libra'), ('BANDEJA', 'Bandeja')], default='BANDEJA', max_length=20),
        ),
    ]
