# Generated by Django 4.2.27 on 2026-02-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_tipo_presentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='TIPO_PRESENTACION',
            new_name='tipo_presentacion',
        ),
    ]
