# Generated by Django 4.2.27 on 2026-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='juridica', max_length=10, verbose_name='Tipo de Persona')),
                ('nit', models.CharField(error_messages={'unique': 'Ya existe un proveedor con este NIT o Cédula.'}, max_length=20, unique=True, verbose_name='Identificación (NIT/Cédula)')),
                ('nombre_contacto', models.CharField(max_length=100, verbose_name='Nombre del Contacto/Empresa')),
                ('correo', models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(error_messages={'unique': 'Este teléfono ya está registrado.'}, max_length=20, unique=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
