# Generated by Django 4.2.27 on 2026-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=100, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(error_messages={'unique': 'Ya existe un proveedor con este NIT o Cédula.'}, max_length=20, unique=True, verbose_name='Identificación (NIT/Cédula)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(max_length=100, verbose_name='Nombre del Contacto/Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(error_messages={'unique': 'Este teléfono ya está registrado.'}, max_length=20, unique=True, verbose_name='Teléfono'),
        ),
    ]
