# Generated by Django 4.2.27 on 2026-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento'),
        ),
    ]
