# Generated by Django 4.2.27 on 2026-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_tipo_persona_alter_proveedor_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está en uso por otro proveedor.'}, max_length=100, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(error_messages={'unique': 'Ya existe un proveedor registrado con este NIT o Cédula.'}, max_length=20, unique=True, verbose_name='Identificación (NIT/Cédula)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(error_messages={'unique': 'Este número de teléfono ya se encuentra registrado.'}, max_length=20, unique=True, verbose_name='Teléfono/Celular'),
        ),
    ]
